# Desafío complementario: Algoritmo de clásificacion - Arbol de decisión
#### Lucas Hernández, Matías Pariente y Diego Bouzada

<!-- # Desafío Complementario: Algoritmo de clásificación - Arbol de decisión -->

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

## Utilizamos un nuevo dataset sin nulos y outliers

In [60]:
df_bicis = pd.read_csv ("C:/Users/dbouzada/Downloads/ecobici2018a2020v3.csv")
df_bicis.head ()

,Unnamed: 0,id_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,genero_usuario,edad_usuario,tiempo_recorrido
0,0,179119,2018-01-01 00:20:14,50,Hospital Rivadavia,2018-01-01 00:47:53,31,Padilla,F,51,27
1,1,179119,2018-04-25 23:30:28,50,Hospital Rivadavia,2018-04-26 02:00:51,50,Hospital Rivadavia,F,51,30
2,2,179119,2018-09-21 19:45:07,129,Velasco,2018-09-21 20:10:24,50,Hospital Rivadavia,F,51,25
3,3,179119,2019-05-19 12:17:03,222,160 - Godoy Cruz y Libertador,2019-05-19 13:20:55,214,142 - Armenia y Gorriti,F,51,3
4,4,400147,2018-01-01 00:20:22,111,Macacha Güemes,2018-01-01 01:09:13,54,Acuña de Figueroa,M,27,48

In [61]:
df_bicis.drop(columns='Unnamed: 0' , inplace=True)

In [62]:
df_bicis.columns

Index(['id_usuario', 'fecha_origen_recorrido', 'id_estacion_origen',
       'nombre_estacion_origen', 'fecha_destino_recorrido',
       'id_estacion_destino', 'nombre_estacion_destino', 'genero_usuario',
       'edad_usuario', 'tiempo_recorrido'],
      dtype='object')

# Primer Ensayo
### Intentamos realizar el algoritmo con el data set completo, pero nos arroja error el get_dummies

In [63]:
df_estaciones2 = df_bicis.iloc[:, [0,2,5]]
df_estaciones2.shape

In [65]:
#### Esta da error el get dummies ####
#bicis_dummies = pd.get_dummies(df_estaciones2, columns = ["id_usuario", "id_estacion_origen", 'id_estacion_destino'])
#bicis_dummies

# Segundo Ensayo
### Aquí intentamos con cuatro estaciones y nos tomó todo bien

In [66]:
df_estaciones = df_bicis[df_bicis.id_estacion_origen.isin([14 , 33 , 9, 29]) & #Los nombres son: Facultad de Medicina" , "Pacífico", "Parque Las Heras", "Plaza Italia"
               df_bicis.id_estacion_destino.isin([14 , 33, 9, 29])] # Los nombres son: "Facultad de Medicina" , "Pacífico", "Parque Las Heras", "Parque Centenario"
df_estaciones.head()

,id_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,genero_usuario,edad_usuario,tiempo_recorrido
259,347609,2018-01-03 20:25:43,29,Parque Centenario,2018-01-03 20:31:03,29,Parque Centenario,M,26,5
2512,439739,2020-08-08 18:14:21,29,029 - Parque Centenario,2020-08-08 18:43:39,29,029 - Parque Centenario,M,47,29
2774,404318,2018-10-13 16:41:55,14,Pacífico,2018-10-13 16:48:37,14,Pacífico,M,27,6
2807,417673,2018-02-08 23:43:36,9,Parque Las Heras,2018-02-08 23:56:52,9,Parque Las Heras,M,19,13
3163,463628,2018-06-23 02:49:23,9,Parque Las Heras,2018-06-23 03:04:54,9,Parque Las Heras,M,23,15

In [67]:
df_estaciones3 = df_estaciones.iloc[:, [0,2,5,9]]
df_estaciones3.head()

      id_usuario  id_estacion_origen  id_estacion_destino  tiempo_recorrido
259       347609                  29                   29                 5
2512      439739                  29                   29                29
2774      404318                  14                   14                 6
2807      417673                   9                    9                13
3163      463628                   9                    9                15

In [68]:
bicis_dummies2 = pd.get_dummies(df_estaciones3, columns = ["id_usuario", "id_estacion_origen", 'id_estacion_destino'])
bicis_dummies2

,tiempo_recorrido,id_usuario_53,id_usuario_389,id_usuario_489,id_usuario_1689,id_usuario_2077,id_usuario_2353,id_usuario_2450,id_usuario_2719,id_usuario_3018,...,id_usuario_672127,id_usuario_672131,id_estacion_origen_9,id_estacion_origen_14,id_estacion_origen_29,id_estacion_origen_33,id_estacion_destino_9,id_estacion_destino_14,id_estacion_destino_29,id_estacion_destino_33
259,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2512,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2774,6,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2807,13,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
3163,15,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804215,11,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3804224,34,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3804227,25,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3804228,43,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3804229,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [69]:
X = bicis_dummies2
y = df_estaciones3.tiempo_recorrido

In [70]:
from sklearn.model_selection import train_test_split #Importamos la libreria para separar en train y test

#Me quedo con 30% para test y 70% para train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [71]:
from sklearn.tree import DecisionTreeClassifier #Importamos el modelo
tree = DecisionTreeClassifier(max_depth=20, random_state = 42) #Creamos el modelo

In [72]:
#Entrenamos el modelo
tree.fit(X_train,y_train) #Entrenamos el modelo

DecisionTreeClassifier(max_depth=20, random_state=42)

In [73]:
y_train_pred = tree.predict(X_train) #Prediccion en Train
y_test_pred = tree.predict(X_test) #Prediccion en Test

In [74]:
from sklearn.metrics import accuracy_score

#Calculo el accuracy en Train
train_accuracy = accuracy_score(y_train, y_train_pred)

#Calculo el accuracy en Test
test_accuracy = accuracy_score(y_test, y_test_pred)

print('% de aciertos sobre el set de entrenamiento:', train_accuracy)
print('% de aciertos sobre el set de evaluación:',test_accuracy)

% de aciertos sobre el set de entrenamiento: 0.8072602739726027
% de aciertos sobre el set de evaluación: 0.8224657534246576

# Gráficos
#### Realizamos algunas pruebas pero nos da error al graficarlas.

In [75]:
tree.plot_tree(tree, feature_names= X, class_names=y, filled = True)
plt.show()

In [76]:
plt.figure(figsize=(20,12))
tree.plot_tree(tree, feature_names= X_train.columns, max_depth=5)
plt.tight_layout()
plt.show()